name: Build EXE

on: [push]

permissions:
  contents: write  # Allows creating releases
  issues: write    # (Optional) Allows issue/comment interactions if needed

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - run: pip install pyinstaller numpy noise matplotlib svgwrite rich

      - run: pyinstaller --onefile create.py  # Change 'create.py' to your script

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.sha }}  # Valid tag name with a prefix
          release_name: Release ${{ github.sha }}
          body: ${{ github.event.head_commit.message }}  # Commit message as release notes
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload EXE to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/create.exe  # Ensure this is the correct path to your executable
          asset_name: create.exe
          asset_content_type: application/octet-stream
